import type { Metadata } from "next";

import "./style/chatstyle.css";
import"./style/navestyle.css";
import"./style/homestyle.css";
import"./style/slidebarstyle.css";
import "./style/style.css";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
      
    </html>
  );
}
